//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empleados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSolicitudes
    {
        public int Id_solicitud { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Resumen { get; set; }
        public Nullable<int> Id_Empleado_s { get; set; }
    
        public virtual tblEmpleados tblEmpleados { get; set; }
    }
}
